server:
  port: 8081

spring:
  application:
    name: api

grpc:
  client:
    people-service:
      address: 'static://127.0.0.1:9090'
      negotiationType: PLAINTEXT
      enable-keep-alive: true
      keep-alive-without-calls: true
      max-inbound-message-size: 4194304 # 4 MB